[INFO     2013-10-26 13:13:02,279 bulkloader.py] Logging to bulkloader-log-20131026.131302
[INFO     2013-10-26 13:13:02,279 bulkloader.py] Throttling transfers:
[INFO     2013-10-26 13:13:02,279 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2013-10-26 13:13:02,279 bulkloader.py] HTTP connections: 8/second
[INFO     2013-10-26 13:13:02,279 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2013-10-26 13:13:02,279 bulkloader.py] Batch Size: 10
[INFO     2013-10-26 13:13:07,104 bulkloader.py] Opening database: bulkloader-progress-20131026.131302.sql3
[DEBUG    2013-10-26 13:13:07,468 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: started
[DEBUG    2013-10-26 13:13:07,469 adaptive_thread_pool.py] [WorkerThread-1] WorkerThread: started
[DEBUG    2013-10-26 13:13:07,469 adaptive_thread_pool.py] [WorkerThread-2] WorkerThread: started
[DEBUG    2013-10-26 13:13:07,470 adaptive_thread_pool.py] [WorkerThread-3] WorkerThread: started
[DEBUG    2013-10-26 13:13:07,471 adaptive_thread_pool.py] [WorkerThread-4] WorkerThread: started
[DEBUG    2013-10-26 13:13:07,471 adaptive_thread_pool.py] [WorkerThread-5] WorkerThread: started
[DEBUG    2013-10-26 13:13:07,471 adaptive_thread_pool.py] [WorkerThread-6] WorkerThread: started
[DEBUG    2013-10-26 13:13:07,472 adaptive_thread_pool.py] [WorkerThread-7] WorkerThread: started
[DEBUG    2013-10-26 13:13:07,472 adaptive_thread_pool.py] [WorkerThread-8] WorkerThread: started
[DEBUG    2013-10-26 13:13:07,473 adaptive_thread_pool.py] [WorkerThread-9] WorkerThread: started
[DEBUG    2013-10-26 13:13:07,473 bulkloader.py] Configuring remote_api. url_path = /_ah/remote_api, servername = localhost:8080
[DEBUG    2013-10-26 13:13:07,473 bulkloader.py] Bulkloader using app_id: dev~s~measureheaven
[INFO     2013-10-26 13:13:07,473 bulkloader.py] Connecting to localhost:8080/_ah/remote_api
[DEBUG    2013-10-26 13:13:07,496 bulkloader.py] [Thread-11] ProgressTrackerThread: started
[DEBUG    2013-10-26 13:13:07,497 bulkloader.py] [Thread-12] DataSourceThread: started
[INFO     2013-10-26 13:13:07,497 bulkloader.py] Starting import; maximum 10 entities per post
[DEBUG    2013-10-26 13:13:07,501 adaptive_thread_pool.py] [WorkerThread-0] Got work item [1-10]
[ERROR    2013-10-26 13:13:07,507 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread:
Traceback (most recent call last):
  File "/home/diegob/Google/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 175, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/home/diegob/Google/google_appengine/google/appengine/tools/bulkloader.py", line 756, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/diegob/Google/google_appengine/google/appengine/tools/bulkloader.py", line 925, in _TransferItem
    self.content = self.request_manager.EncodeContent(self.rows)
  File "/home/diegob/Google/google_appengine/google/appengine/tools/bulkloader.py", line 1429, in EncodeContent
    entity = loader.create_entity(values, key_name=key, parent=parent)
  File "/home/diegob/Google/google_appengine/google/appengine/tools/bulkloader.py", line 2775, in create_entity
    properties[name] = converter(val)
  File "DataStructs/MeasurementLoader.py", line 16, in <lambda>
    [('time', lambda x: datetime.datetime.strptime(x, "%Y-%m-%dT%H:%M:%S").date()),
  File "/usr/lib64/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .00
[DEBUG    2013-10-26 13:13:07,513 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: exiting
[INFO     2013-10-26 13:13:07,513 adaptive_thread_pool.py] [WorkerThread-1] Backing off due to errors: 1.0 seconds
[INFO     2013-10-26 13:13:07,747 bulkloader.py] Unexpected thread death: WorkerThread-0
[INFO     2013-10-26 13:13:07,747 bulkloader.py] An error occurred. Shutting down...
[DEBUG    2013-10-26 13:13:07,751 adaptive_thread_pool.py] [WorkerThread-4] WorkerThread: exiting
[DEBUG    2013-10-26 13:13:07,751 adaptive_thread_pool.py] [WorkerThread-5] WorkerThread: exiting
[DEBUG    2013-10-26 13:13:07,751 adaptive_thread_pool.py] [WorkerThread-3] WorkerThread: exiting
[DEBUG    2013-10-26 13:13:07,752 adaptive_thread_pool.py] [WorkerThread-6] WorkerThread: exiting
[DEBUG    2013-10-26 13:13:07,752 adaptive_thread_pool.py] [WorkerThread-8] WorkerThread: exiting
[DEBUG    2013-10-26 13:13:07,752 adaptive_thread_pool.py] [WorkerThread-7] WorkerThread: exiting
[DEBUG    2013-10-26 13:13:07,752 adaptive_thread_pool.py] [WorkerThread-2] WorkerThread: exiting
[DEBUG    2013-10-26 13:13:07,752 adaptive_thread_pool.py] [WorkerThread-9] WorkerThread: exiting
[DEBUG    2013-10-26 13:13:07,764 adaptive_thread_pool.py] [WorkerThread-1] WorkerThread: exiting
[DEBUG    2013-10-26 13:13:07,795 bulkloader.py] [Thread-12] DataSourceThread: exiting
[DEBUG    2013-10-26 13:13:07,817 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2013-10-26 13:13:07,817 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2013-10-26 13:13:07,817 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2013-10-26 13:13:07,817 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2013-10-26 13:13:07,817 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2013-10-26 13:13:07,817 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2013-10-26 13:13:07,817 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2013-10-26 13:13:07,818 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2013-10-26 13:13:07,818 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2013-10-26 13:13:07,818 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[ERROR    2013-10-26 13:13:07,818 adaptive_thread_pool.py] Error in WorkerThread-0: unconverted data remains: .00
[DEBUG    2013-10-26 13:13:07,818 adaptive_thread_pool.py] Traceback (most recent call last):
  File "/home/diegob/Google/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 175, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/home/diegob/Google/google_appengine/google/appengine/tools/bulkloader.py", line 756, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/diegob/Google/google_appengine/google/appengine/tools/bulkloader.py", line 925, in _TransferItem
    self.content = self.request_manager.EncodeContent(self.rows)
  File "/home/diegob/Google/google_appengine/google/appengine/tools/bulkloader.py", line 1429, in EncodeContent
    entity = loader.create_entity(values, key_name=key, parent=parent)
  File "/home/diegob/Google/google_appengine/google/appengine/tools/bulkloader.py", line 2775, in create_entity
    properties[name] = converter(val)
  File "DataStructs/MeasurementLoader.py", line 16, in <lambda>
    [('time', lambda x: datetime.datetime.strptime(x, "%Y-%m-%dT%H:%M:%S").date()),
  File "/usr/lib64/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .00

[DEBUG    2013-10-26 13:13:07,818 bulkloader.py] Waiting for progress_thread to terminate...
[DEBUG    2013-10-26 13:13:07,913 bulkloader.py] [Thread-11] ProgressTrackerThread: exiting
[DEBUG    2013-10-26 13:13:07,933 bulkloader.py] ... done.
[INFO     2013-10-26 13:13:07,933 bulkloader.py] 1020 entities total, 0 previously transferred
[INFO     2013-10-26 13:13:07,933 bulkloader.py] 0 entities (937 bytes) transferred in 5.7 seconds
[INFO     2013-10-26 13:13:07,933 bulkloader.py] Some entities not successfully transferred
